### ISSUE TITLE
How to manage offline widget on multiple page ? 

### ISSUE THREAD

**Issue by patelmanjeet** [jogboms/flutter_offline#15]
My Application have n number of pages, for now to show offline page I need to integrate this (OfflineBuilder) Widget on each page. 

Is any way to show offline Widget on top of any page from single location? so, It will not subscribe/unsubscribe network stream on each page and easy to manage.

**Comment by jogboms** [comment]
@patelmanjeet It will depend on how your app is structured. Its all composition so this widget can be placed at any point in your app that allows it to affect other navigation trees. 

I can't say how you'd do that as i haven't tried placing it above the `WidgetApp`, but maybe the `WidgetApp` `builder` callback. I haven't tried that but i know i saw it somewhere.
