### ISSUE TITLE
Maintain the change log

### ISSUE THREAD

**Issue by artob** [jogboms/flutter_offline#16]
Whenever I'm upgrading my dependencies and reviewing upgraded packages' [CHANGELOG.md tabs](https://pub.dartlang.org/packages/flutter_offline#-changelog-tab-) on Pub, I'm missing any explanation of [what changed in new releases of flutter_offline](https://github.com/jogboms/flutter_offline/blob/master/CHANGELOG.md).

It would be great to keep a proper change log to let users know whether an upgrade is likely to break their app or not.

If the notion has been to not maintain the change log until a 1.0 release, well, this package de facto already has a lot of users and perhaps it ought to be a version 1.0, semantically versioned and with a change log. Just a thought.

**Comment by jogboms** [comment]
Thanks @artob 
You guessed right actually, why I didn't really focus on the CHANGELOG was because of the <1.0 releases.
And yes the next update would take it to 1.0.
Thanks for your interest and observation. 👍
