### ISSUE TITLE
connectivity plugin - android build deprecation warning

### ISSUE THREAD

**Issue by hey24sheep** [jogboms/flutter_offline#24]
After adding the plugin to a new flutter application (Stable Channel, migrated to androidX) a deprecation warning is present when running a build (Android only).

The warning presented:

```
Note: /Users/dwulff/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.2/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by epicquestgames** [comment]
Any update on this ?

**Comment by git-xbits** [comment]
Any chance to resolve this issue? Same problem where in last version.

**Comment by jogboms** [comment]
If someone can help pick this up before i do, it will be really nice.

**Comment by git-xbits** [comment]
I'll try this weekend, I never make plugins before.
