### ISSUE TITLE
Androidx incompatible

### ISSUE THREAD

**Issue by akshaybenk** [jogboms/flutter_offline#28]
Am using the flutter offline, package version - 0.3.0
this depends on connectivity package versioned - 0.4.6

When I try to build release apk , the following output is thrown resulting in build failure.

The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin connectivity...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done 1.2s

FAILURE: Build failed with an exception.

What went wrong:
A problem occurred configuring root project 'connectivity'.
SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 0s

The plugin connectivity could not be built due to the issue above.

Any help on how to fix this?

**Comment by jogboms** [comment]
Hey @akshaybenk 
The error might not be too obvious, but do you have your `ANDROID_HOME` configured properly?
