### ISSUE TITLE
Add Duration for the connectivityBuilder

### ISSUE THREAD

**Issue by ram231** [jogboms/flutter_offline#3]
Great Package you made, and it made easy for determining if the user has connected.
I have this kind of issue when I want to have a Duration for that Connectivity. I want to hide that widget once the connection is either online or offline in a matter of duration.

**Comment by jogboms** [comment]
Thanks @ram231.
This is actually being enhanced, give me a few.

**Comment by rammesaran** [comment]
Hi, What property to be used to hide that widget once the connection is either online or offline
