### ISSUE TITLE
remove child property

### ISSUE THREAD

**Issue by chitgoks** [jogboms/flutter_offline#31]
widget should at least be inside the builder. 

there is no way to get the connectivityresult if you place the main widget in the child property and it needs to check connectivity

**Comment by jogboms** [comment]
The `child` represents a piece of widget tree that doesn't have a direct dependency on the connectivity result so that it doesn't have to be recomputed every time the result changes. Its a performance optimisation pattern borrowed from flutter as seen in the `AnimationBuilder`.
