### ISSUE TITLE
PlatformException(error, NetworkCallback was not registered, null, null) 

### ISSUE THREAD

**Issue by Sathi789888** [jogboms/flutter_offline#34]
I need flutter offline to check the status of the connection but I got the below mentioned error because of  connectivity: ^0.4.5+3 dependencies.

```
The following PlatformException was thrown while de-activating platform stream on channel plugins.flutter.io/connectivity_status:
**PlatformException(error, NetworkCallback was not registered, null, null)**

When the exception was thrown, this was the stack: 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:552:29)
...
```

**Comment by MohYasinMohammadi** [comment]
I have the same error with connectivity 0.4.5+3 and flutter_offline 0.3.0.

**Comment by Matej-Hlatky** [comment]
Well, this appears to be bug in the [connectivity](https://pub.dev/packages/connectivity) package - see issue https://github.com/flutter/flutter/issues/68265 
It should be fixed in version [2.0.2](https://pub.dev/packages/connectivity/changelog#202).

**Comment by Sathi789888** [comment]
flutter_offline plugin doesn't allow to update the connectivity package

**Comment by Matej-Hlatky** [comment]
> flutter_offline plugin doesn't allow to update the connectivity package

We manage to workaround this by using [Dependency overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides) like this:
```yaml
dependency_overrides:
  # for flutter_offline to fix PlatformException(error, NetworkCallback was not registered, null, null)
  connectivity: ^2.0.2
```

**Comment by Sathi789888** [comment]
Thank You for your suggesstion

**Comment by Matej-Hlatky** [comment]
@jogboms , would you kindly make new version with updated `connectivity` dependency? Thanks
