### ISSUE TITLE
PlatformException(error, NetworkCallback was not registered, null, null)

### ISSUE THREAD

**Issue by mobashshirurrahman** [jogboms/flutter_offline#35]
PlatformException(error, NetworkCallback was not registered, null, null) 

Network call back error is showing when I am using the flutter offline package. plz, guide how should I solve it.

**Comment by cedvdb** [comment]
I have the same error and from what I understand it's a problem with the connectivity package dep that needs to be updated to a newer version. Either override it or just use that package instead
