### ISSUE TITLE
[ How to use it on an "App level" ? ]

### ISSUE THREAD

**Issue by Gobmichet** [jogboms/flutter_offline#54]
Hi,
This plugin is very cool but clearly it's a problem to wrap every single screen in an OfflineBuilder()...
That's a lot of duplicated / boilerplate code for each one.

Does someone managed to "extract" the code of the OfflineBuilder() to put it in the main.dart for example ?

Thanks in advance

**Comment by JCKodel** [comment]
????

just

```dart
MaterialApp(
  ...
  home: OfflineBuilder(
  ...
  child: Your_Old_Home
  ),
)
```
