### ISSUE TITLE
[   +3 ms] Swift Compiler Error (Xcode): Cannot find type 'Reachability' in scope

### ISSUE THREAD

**Issue by s2yed** [jogboms/flutter_offline#55]
[   +3 ms] Swift Compiler Error (Xcode): Cannot find type 'Reachability' in scope
           /Users/tebalink/development/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity_plus-2.3.6/ios/Classes/ReachabilityConnectivityProvider.swift:3:29

**Comment by sarinupreti2021** [comment]
+1
