### ISSUE TITLE
depend on `network_info_plus: ^4.0.0`

### ISSUE THREAD

**Issue by dJani97** [jogboms/flutter_offline#57]
flutter_offline currently depends on  `network_info_plus: ^2.1.2`, which is a really old version. Version 3 and even version 4 were released since then.

Please depend on `network_info_plus: ^4.0.0`.

**Comment by AngeloAvv** [comment]
Hey @dJani97 , I opened a [PR](https://github.com/jogboms/flutter_offline/pull/58) to fix this issue
