### ISSUE TITLE
not working on ios

### ISSUE THREAD

**Issue by gedw99** [jogboms/flutter_offline#6]
i noticed on IOS the text does not even show, so it may be working but i cant see it working.

I can force it to show the GUI if i go into demo 3 and toggle the wifi.

Try it yourself..

IOS
![ios](https://user-images.githubusercontent.com/20677314/45292108-799aad00-b4f4-11e8-9767-f14823b723de.png)

**Comment by jogboms** [comment]
Thanks @gedw99, There must be a regression of some sorts. I'd verify and get back to this.
