### ISSUE TITLE
A constructor invocation can't have type arguments on the constructor name.

### ISSUE THREAD

**Issue by Abgaryan** [jogboms/flutter_offline#8]
Compiler message:
flutter/.pub-cache/hosted/pub.dartlang.org/flutter_offline-0.2.1/lib/src/utils.dart:13:30: Error: A constructor invocation can't have type arguments on the constructor name.
Try to place the type arguments on the class name.
`    return StreamTransformer.fromHandlers<ConnectivityResult,`
                             ^^^^^^^^^^^^
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.11.3, on Mac OS X 10.13.6 17G65, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[!] VS Code (version 1.28.2)
[✓] Connected device (1 available)
```

**Comment by Abgaryan** [comment]
@jogboms  any updates on this issue ?

**Comment by zzzz1997** [comment]
> 
> 
> @jogboms any updates on this issue ?



> 
> 
> Compiler message:
> flutter/.pub-cache/hosted/pub.dartlang.org/flutter_offline-0.2.1/lib/src/utils.dart:13:30: Error: A constructor invocation can't have type arguments on the constructor name.
> Try to place the type arguments on the class name.
> ` return StreamTransformer.fromHandlers<ConnectivityResult,`
> ^^^^^^^^^^^^
> 
> ```
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel dev, v0.11.3, on Mac OS X 10.13.6 17G65, locale en-DE)
> [✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
> [✓] Android Studio (version 3.2)
> [!] VS Code (version 1.28.2)
> [✓] Connected device (1 available)
> ```



> 
> 
> Compiler message:
> flutter/.pub-cache/hosted/pub.dartlang.org/flutter_offline-0.2.1/lib/src/utils.dart:13:30: Error: A constructor invocation can't have type arguments on the constructor name.
> Try to place the type arguments on the class name.
> ` return StreamTransformer.fromHandlers<ConnectivityResult,`
> ^^^^^^^^^^^^
> 
> ```
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel dev, v0.11.3, on Mac OS X 10.13.6 17G65, locale en-DE)
> [✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
> [✓] Android Studio (version 3.2)
> [!] VS Code (version 1.28.2)
> [✓] Connected device (1 available)
> ```

I deleted ‘<ConnectivityResult, ConnectivityResult>’ to solve this problem.
`return StreamTransformer.fromHandlers~~<ConnectivityResult,~~
        ~~ConnectivityResult>~~(
      handleData:`

**Comment by jogboms** [comment]
Sorry for the delays guys. I already fixed, forgot to publish. Its now on v0.2.2
